# Example configuration for jobx market analysis
# This file demonstrates the structure for analyzing BCBA positions across multiple markets

job_title: "Board Certified Behavioral Analyst"
search_radius: 25  # miles
results_per_location: 200
batch_size: 5  # Number of locations to search concurrently

markets:
  - name: "Northeast"
    regions:
      - name: "New England"
        locations:
          - name: "Boston Metro"
            address: "Boston, MA"
            zip_code: "02108"
          - name: "Cambridge"
            address: "Cambridge, MA"
            zip_code: "02139"
          - name: "Providence"
            address: "Providence, RI"
            zip_code: "02903"
          - name: "Hartford"
            address: "Hartford, CT"
            zip_code: "06103"
          - name: "Portland ME"
            address: "Portland, ME"
            zip_code: "04101"
      
      - name: "Mid-Atlantic"
        locations:
          - name: "Manhattan"
            address: "New York, NY"
            zip_code: "10001"
          - name: "Brooklyn"
            address: "Brooklyn, NY"
            zip_code: "11201"
          - name: "Philadelphia"
            address: "Philadelphia, PA"
            zip_code: "19102"
          - name: "Newark"
            address: "Newark, NJ"
            zip_code: "07102"
          - name: "Baltimore"
            address: "Baltimore, MD"
            zip_code: "21201"

  - name: "Southeast"
    regions:
      - name: "South Atlantic"
        locations:
          - name: "DC Metro"
            address: "Washington, DC"
            zip_code: "20001"
          - name: "Arlington"
            address: "Arlington, VA"
            zip_code: "22201"
          - name: "Richmond"
            address: "Richmond, VA"
            zip_code: "23219"
          - name: "Charlotte"
            address: "Charlotte, NC"
            zip_code: "28202"
          - name: "Raleigh"
            address: "Raleigh, NC"
            zip_code: "27601"
      
      - name: "Florida"
        locations:
          - name: "Miami"
            address: "Miami, FL"
            zip_code: "33130"
          - name: "Fort Lauderdale"
            address: "Fort Lauderdale, FL"
            zip_code: "33301"
          - name: "Orlando"
            address: "Orlando, FL"
            zip_code: "32801"
          - name: "Tampa"
            address: "Tampa, FL"
            zip_code: "33602"
          - name: "Jacksonville"
            address: "Jacksonville, FL"
            zip_code: "32202"

  - name: "Midwest"
    regions:
      - name: "Great Lakes"
        locations:
          - name: "Chicago"
            address: "Chicago, IL"
            zip_code: "60601"
          - name: "Milwaukee"
            address: "Milwaukee, WI"
            zip_code: "53202"
          - name: "Detroit"
            address: "Detroit, MI"
            zip_code: "48226"
          - name: "Cleveland"
            address: "Cleveland, OH"
            zip_code: "44114"
          - name: "Indianapolis"
            address: "Indianapolis, IN"
            zip_code: "46204"
      
      - name: "Plains"
        locations:
          - name: "Minneapolis"
            address: "Minneapolis, MN"
            zip_code: "55401"
          - name: "St. Louis"
            address: "St. Louis, MO"
            zip_code: "63101"
          - name: "Kansas City"
            address: "Kansas City, MO"
            zip_code: "64105"
          - name: "Omaha"
            address: "Omaha, NE"
            zip_code: "68102"
          - name: "Des Moines"
            address: "Des Moines, IA"
            zip_code: "50309"

  - name: "Southwest"
    regions:
      - name: "Texas"
        locations:
          - name: "Houston"
            address: "Houston, TX"
            zip_code: "77002"
          - name: "Dallas"
            address: "Dallas, TX"
            zip_code: "75201"
          - name: "Austin"
            address: "Austin, TX"
            zip_code: "78701"
          - name: "San Antonio"
            address: "San Antonio, TX"
            zip_code: "78205"
          - name: "Fort Worth"
            address: "Fort Worth, TX"
            zip_code: "76102"
      
      - name: "Mountain"
        locations:
          - name: "Phoenix"
            address: "Phoenix, AZ"
            zip_code: "85004"
          - name: "Tucson"
            address: "Tucson, AZ"
            zip_code: "85701"
          - name: "Denver"
            address: "Denver, CO"
            zip_code: "80202"
          - name: "Salt Lake City"
            address: "Salt Lake City, UT"
            zip_code: "84101"
          - name: "Las Vegas"
            address: "Las Vegas, NV"
            zip_code: "89101"

  - name: "West"
    regions:
      - name: "California"
        locations:
          - name: "Los Angeles"
            address: "Los Angeles, CA"
            zip_code: "90012"
          - name: "San Diego"
            address: "San Diego, CA"
            zip_code: "92101"
          - name: "San Francisco"
            address: "San Francisco, CA"
            zip_code: "94102"
          - name: "San Jose"
            address: "San Jose, CA"
            zip_code: "95113"
          - name: "Sacramento"
            address: "Sacramento, CA"
            zip_code: "95814"
      
      - name: "Pacific Northwest"
        locations:
          - name: "Seattle"
            address: "Seattle, WA"
            zip_code: "98101"
          - name: "Portland"
            address: "Portland, OR"
            zip_code: "97204"
          - name: "Spokane"
            address: "Spokane, WA"
            zip_code: "99201"
          - name: "Eugene"
            address: "Eugene, OR"
            zip_code: "97401"
          - name: "Boise"
            address: "Boise, ID"
            zip_code: "83702"