# Test config for anti-detection features
meta:
  version: 1.0
  created_date: 2025-09-11
  last_updated: 2025-09-11

roles:
  - id: bcba
    name: Board Certified Behavior Analyst
    pay_type: salary
    default_unit: USD/year
    search_terms:
      - "Board Certified Behavior Analyst"
      - "Board Certified Behavioral Analyst"
      - "BCBA"
      - "Behavior Analyst"
      - "Behavioral Analyst"

search:
  radius_miles: 25
  results_per_location: 10  # Very small for testing
  batch_size: 1

regions:
  - name: "Test Region"
    markets:
      - name: "Miami"
        paybands:
          bcba:
            min: 70000
            max: 90000
        centers:
          - code: "MIA001"
            name: "Miami Test Center"
            address_1: "123 Test St"
            city: "Miami"
            state: "FL"
            zip_code: "33101"
            paybands:
              bcba:
                min: 72000
                max: 88000
          - code: "MIA002"
            name: "Miami Beach Test"
            address_1: "456 Beach Rd"
            city: "Miami Beach"
            state: "FL"
            zip_code: "33139"
            paybands:
              bcba:
                min: 73000
                max: 89000